### ISSUE TITLE
System.IndexOutOfRangeException for Suggest

### ISSUE THREAD

**Issue by shell** [aarondandy/WeCantSpell.Hunspell#71]
Hello,

I'm using library for spellcheck and suggestions. Nothing fancy in initialization:

```csharp
hunspell = WordList.CreateFromStreams(dictionaryStream, affixStream);
hunspell.Suggest(word);
```
It's running on net6.0: `<TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>`
Here are my affix file and dictionary file [en.zip](https://github.com/aarondandy/WeCantSpell.Hunspell/files/8328582/en.zip) (pretty sure I've got it from open sources, so it's safe to share)

Sometimes I get exception: `System.IndexOutOfRangeException` when trying to call `.Suggest()`
I can't reproduce locally, for given inputs and outputs that produce exception. This is happened in production/stage system over multiple days. For past 14 days and 400k calls, it happened 7 times so far.

Here is a stack trace that I received:
```log
[14:53:56.828](154)  Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WeCantSpell.Hunspell.WordList.QuerySuggest.LeftCommonSubstring(String s1, String s2)
   at WeCantSpell.Hunspell.WordList.QuerySuggest.NGramSuggest(List`1 wlst, String word, CapitalizationType capType)
   at WeCantSpell.Hunspell.WordList.QuerySuggest.Suggest(String word)
```

It happened for following suggestion requests: `nth`, `gua`, `gua`, `colo`, `leav`, `Jira`, `o`

I've just updated to version 3.1.1 to see if it will help, and I have high hopes about 4.0. I'll report later with my findings

**Comment by aarondandy** [comment]
😬 I'll have to dig into this. I'll also try to get a hotfix on the v3 branch for it too.

**Comment by aarondandy** [comment]
I couldn't get a reproduction of that either with those inputs but it definitely helps, I appreciate that. The bug is obvious to me now though and I do have a failing case to work with. If you explicitly add `""` as a dictionary word you can get this to happen, but I doubt that is the case here. I'll see if I can get a v3 release out for that and also make sure this fix ends up in v4.

**Comment by shell** [comment]
That might be it! I actually merge multiple dictionaries together in a stream, there might be `""` sneaking somewhere. Thanks for the tip!

**Comment by aarondandy** [comment]
Give [3.1.2](https://www.nuget.org/packages/WeCantSpell.Hunspell/3.1.2) a try and see if that works better for you. Feel free to re-open if you think it's still an issue.

**Comment by aarondandy** [comment]
Also, be very careful "merging" dictionaries together as the first line that is a number is a count of the number of words in the file, but I don't _think_ my code requires it. You might want to avoid random numbers ending up in your word list. Also the aff files are pretty complicated and probably won't work if you just concat them together.

**Comment by shell** [comment]
Confirming that I no longer see exceptions happening. Thanks for fixing again
